queue:
    pattern:  /
    defaults: { _controller: QueuesBundle:YourQueue:index }

queue_customer_served:
    pattern:  /klient-obsluzony/{id}
    defaults: { _controller: QueuesBundle:YourQueue:customerServed }

queue_serve_next:
    pattern:  /przyjmij-kolejna-osobe/{id}
    defaults: { _controller: QueuesBundle:YourQueue:serveNext }

queue_get_ussd:
    pattern:  /odbierz-ussd/
    defaults: { _controller: QueuesBundle:Enqueue:enqueue }